language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - pear install pear.corneltek.com/PHPUnit_TestMore
  - php onion install
  - composer install --dev

script: phpunit
