language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - php onion install
  - composer install
#   - ./scripts/compile.sh
#  - php onion.phar -d build --pyrus

script: phpunit
#  notifications:
#    irc: "irc.freenode.org#onion-dev"
